apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-server
  namespace: default
spec:
  secretName: webhook-server-cert
  dnsNames:
  - mutate.default.svc
  - mutate.default.svc.cluster.local
  issuerRef:
    name: mutate-self-signer
    kind: Issuer
