apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mutate
  name: mutate
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mutate
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mutate
    spec:
      containers:
      - image: docker.io/shkatara/mutating-webhook:demo-v1
        imagePullPolicy: Always
        name: mutating-webhook
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /certs
          name: webhook-server-cert
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: webhook-server-cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
