apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutate-webhook-inject
  annotations:
    cert-manager.io/inject-ca-from: default/webhook-server
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: mutate
      namespace: default
      path: /inject
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mutating-webhook.trivago.io
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
      - kube-node-lease
      - kube-public
      - gcp-auth
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: Namespaced
  sideEffects: None
  timeoutSeconds: 10
