apiVersion: v1
kind: Service
metadata:
  labels:
    app: mutate
  name: mutate
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: mutate
  sessionAffinity: None
  type: ClusterIP
